contact_links:
  - name: 📚 Documentation
    url: https://antelopejs.com/
    about: Check documentation for usage
  - name: 💬 Discussions
    url: https://github.com/AntelopeJS/antelopejs/discussions
    about: Use discussions if you have an idea for improvement and asking questions
